import { useState, useEffect, useCallback } from 'react';

export interface LocationSuggestion {
  id: string;
  name: string;
  country: string;
  state?: string;
  displayName: string;
}

interface UseLocationAutocompleteOptions {
  debounceMs?: number;
  minLength?: number;
}

// Simple city database for autocomplete
const CITY_DATABASE = [
  { name: 'New York', state: 'NY', country: 'United States' },
  { name: 'Los Angeles', state: 'CA', country: 'United States' },
  { name: 'Chicago', state: 'IL', country: 'United States' },
  { name: 'Houston', state: 'TX', country: 'United States' },
  { name: 'Phoenix', state: 'AZ', country: 'United States' },
  { name: 'Philadelphia', state: 'PA', country: 'United States' },
  { name: 'San Antonio', state: 'TX', country: 'United States' },
  { name: 'San Diego', state: 'CA', country: 'United States' },
  { name: 'Dallas', state: 'TX', country: 'United States' },
  { name: 'San Jose', state: 'CA', country: 'United States' },
  { name: 'Austin', state: 'TX', country: 'United States' },
  { name: 'Jacksonville', state: 'FL', country: 'United States' },
  { name: 'Fort Worth', state: 'TX', country: 'United States' },
  { name: 'Columbus', state: 'OH', country: 'United States' },
  { name: 'Charlotte', state: 'NC', country: 'United States' },
  { name: 'San Francisco', state: 'CA', country: 'United States' },
  { name: 'Indianapolis', state: 'IN', country: 'United States' },
  { name: 'Seattle', state: 'WA', country: 'United States' },
  { name: 'Denver', state: 'CO', country: 'United States' },
  { name: 'Washington', state: 'DC', country: 'United States' },
  { name: 'Boston', state: 'MA', country: 'United States' },
  { name: 'El Paso', state: 'TX', country: 'United States' },
  { name: 'Nashville', state: 'TN', country: 'United States' },
  { name: 'Detroit', state: 'MI', country: 'United States' },
  { name: 'Oklahoma City', state: 'OK', country: 'United States' },
  { name: 'Portland', state: 'OR', country: 'United States' },
  { name: 'Las Vegas', state: 'NV', country: 'United States' },
  { name: 'Memphis', state: 'TN', country: 'United States' },
  { name: 'Louisville', state: 'KY', country: 'United States' },
  { name: 'Baltimore', state: 'MD', country: 'United States' },
  { name: 'Milwaukee', state: 'WI', country: 'United States' },
  { name: 'Albuquerque', state: 'NM', country: 'United States' },
  { name: 'Tucson', state: 'AZ', country: 'United States' },
  { name: 'Fresno', state: 'CA', country: 'United States' },
  { name: 'Sacramento', state: 'CA', country: 'United States' },
  { name: 'Mesa', state: 'AZ', country: 'United States' },
  { name: 'Kansas City', state: 'MO', country: 'United States' },
  { name: 'Atlanta', state: 'GA', country: 'United States' },
  { name: 'Long Beach', state: 'CA', country: 'United States' },
  { name: 'Colorado Springs', state: 'CO', country: 'United States' },
  { name: 'Raleigh', state: 'NC', country: 'United States' },
  { name: 'Miami', state: 'FL', country: 'United States' },
  { name: 'Virginia Beach', state: 'VA', country: 'United States' },
  { name: 'Omaha', state: 'NE', country: 'United States' },
  { name: 'Oakland', state: 'CA', country: 'United States' },
  { name: 'Minneapolis', state: 'MN', country: 'United States' },
  { name: 'Tulsa', state: 'OK', country: 'United States' },
  { name: 'Arlington', state: 'TX', country: 'United States' },
  { name: 'Tampa', state: 'FL', country: 'United States' },
  { name: 'New Orleans', state: 'LA', country: 'United States' },
  { name: 'London', country: 'United Kingdom' },
  { name: 'Paris', country: 'France' },
  { name: 'Tokyo', country: 'Japan' },
  { name: 'Sydney', country: 'Australia' },
  { name: 'Toronto', state: 'ON', country: 'Canada' },
  { name: 'Vancouver', state: 'BC', country: 'Canada' },
  { name: 'Berlin', country: 'Germany' },
  { name: 'Madrid', country: 'Spain' },
  { name: 'Rome', country: 'Italy' },
  { name: 'Amsterdam', country: 'Netherlands' },
  { name: 'Barcelona', country: 'Spain' },
  { name: 'Munich', country: 'Germany' },
  { name: 'Zurich', country: 'Switzerland' },
  { name: 'Vienna', country: 'Austria' },
  { name: 'Stockholm', country: 'Sweden' },
  { name: 'Copenhagen', country: 'Denmark' },
  { name: 'Oslo', country: 'Norway' },
  { name: 'Helsinki', country: 'Finland' },
  { name: 'Dublin', country: 'Ireland' },
  { name: 'Edinburgh', country: 'United Kingdom' },
  { name: 'Manchester', country: 'United Kingdom' },
  { name: 'Birmingham', country: 'United Kingdom' },
  { name: 'Glasgow', country: 'United Kingdom' },
  { name: 'Liverpool', country: 'United Kingdom' },
  { name: 'Leeds', country: 'United Kingdom' },
  { name: 'Sheffield', country: 'United Kingdom' },
  { name: 'Bristol', country: 'United Kingdom' },
  { name: 'Newcastle', country: 'United Kingdom' },
  { name: 'Nottingham', country: 'United Kingdom' },
  { name: 'Leicester', country: 'United Kingdom' },
  { name: 'Coventry', country: 'United Kingdom' },
  { name: 'Bradford', country: 'United Kingdom' },
  { name: 'Cardiff', country: 'United Kingdom' },
  { name: 'Belfast', country: 'United Kingdom' },
  { name: 'Derby', country: 'United Kingdom' },
  { name: 'Plymouth', country: 'United Kingdom' },
  { name: 'Wolverhampton', country: 'United Kingdom' },
  { name: 'Southampton', country: 'United Kingdom' },
  { name: 'Swansea', country: 'United Kingdom' },
  { name: 'Salford', country: 'United Kingdom' },
  { name: 'Aberdeen', country: 'United Kingdom' },
  { name: 'Westminster', country: 'United Kingdom' },
  { name: 'Portsmouth', country: 'United Kingdom' },
  { name: 'York', country: 'United Kingdom' },
  { name: 'Peterborough', country: 'United Kingdom' },
  { name: 'Dundee', country: 'United Kingdom' },
  { name: 'Southend-on-Sea', country: 'United Kingdom' },
  { name: 'Norwich', country: 'United Kingdom' },
  { name: 'Preston', country: 'United Kingdom' },
  { name: 'Stoke-on-Trent', country: 'United Kingdom' },
  { name: 'Newport', country: 'United Kingdom' },
  { name: 'Swindon', country: 'United Kingdom' },
  { name: 'Croydon', country: 'United Kingdom' },
  { name: 'Walsall', country: 'United Kingdom' },
  { name: 'Gillingham', country: 'United Kingdom' },
  { name: 'Eastbourne', country: 'United Kingdom' },
  { name: 'Colchester', country: 'United Kingdom' },
  { name: 'Ipswich', country: 'United Kingdom' },
  { name: 'Watford', country: 'United Kingdom' },
  { name: 'Exeter', country: 'United Kingdom' },
  { name: 'Cheltenham', country: 'United Kingdom' },
  { name: 'Gloucester', country: 'United Kingdom' },
  { name: 'Saint Helens', country: 'United Kingdom' },
  { name: 'Basildon', country: 'United Kingdom' },
  { name: 'Worcester', country: 'United Kingdom' },
  { name: 'Maidstone', country: 'United Kingdom' },
  { name: 'Rotherham', country: 'United Kingdom' },
  { name: 'Cambridge', country: 'United Kingdom' },
  { name: 'Doncaster', country: 'United Kingdom' },
  { name: 'Sutton Coldfield', country: 'United Kingdom' },
  { name: 'Blackburn', country: 'United Kingdom' },
  { name: 'Oldham', country: 'United Kingdom' },
  { name: 'Wigan', country: 'United Kingdom' },
  { name: 'Chesterfield', country: 'United Kingdom' },
  { name: 'Stockport', country: 'United Kingdom' },
  { name: 'Brighton', country: 'United Kingdom' },
  { name: 'Preston', country: 'United Kingdom' },
  { name: 'Grimsby', country: 'United Kingdom' },
  { name: 'Royal Tunbridge Wells', country: 'United Kingdom' },
  { name: 'Middlesbrough', country: 'United Kingdom' },
  { name: 'Huddersfield', country: 'United Kingdom' },
  { name: 'Oxford', country: 'United Kingdom' },
  { name: 'Macclesfield', country: 'United Kingdom' },
  { name: 'Blackpool', country: 'United Kingdom' },
  { name: 'Bolton', country: 'United Kingdom' },
  { name: 'Ipswich', country: 'United Kingdom' },
  { name: 'Telford', country: 'United Kingdom' },
  { name: 'York', country: 'United Kingdom' },
  { name: 'Bournemouth', country: 'United Kingdom' },
  { name: 'Norwich', country: 'United Kingdom' },
  { name: 'Peterborough', country: 'United Kingdom' },
  { name: 'Hastings', country: 'United Kingdom' },
  { name: 'Slough', country: 'United Kingdom' },
  { name: 'Worcester', country: 'United Kingdom' },
  { name: 'Hartlepool', country: 'United Kingdom' },
  { name: 'Halifax', country: 'United Kingdom' },
  { name: 'Woking', country: 'United Kingdom' },
  { name: 'Southport', country: 'United Kingdom' },
  { name: 'Maidenhead', country: 'United Kingdom' },
  { name: 'Stafford', country: 'United Kingdom' },
  { name: 'Stevenage', country: 'United Kingdom' },
  { name: 'Dartford', country: 'United Kingdom' },
  { name: 'Weston-super-Mare', country: 'United Kingdom' },
  { name: 'South Shields', country: 'United Kingdom' },
  { name: 'Runcorn', country: 'United Kingdom' },
  { name: 'Tamworth', country: 'United Kingdom' },
  { name: 'Scunthorpe', country: 'United Kingdom' },
  { name: 'Scarborough', country: 'United Kingdom' },
  { name: 'Walsall', country: 'United Kingdom' },
  { name: 'Grimsby', country: 'United Kingdom' },
  { name: 'Shrewsbury', country: 'United Kingdom' },
  { name: 'Gosport', country: 'United Kingdom' },
  { name: 'Luton', country: 'United Kingdom' },
  { name: 'Lowestoft', country: 'United Kingdom' },
  { name: 'Rugby', country: 'United Kingdom' },
  { name: 'Uxbridge', country: 'United Kingdom' },
  { name: 'Inverness', country: 'United Kingdom' },
  { name: 'Keighley', country: 'United Kingdom' },
  { name: 'Paignton', country: 'United Kingdom' },
  { name: 'Bognor Regis', country: 'United Kingdom' },
  { name: 'Folkestone', country: 'United Kingdom' },
  { name: 'Hornchurch', country: 'United Kingdom' },
  { name: 'Salisbury', country: 'United Kingdom' },
  { name: 'Ayr', country: 'United Kingdom' },
  { name: 'Southend-on-Sea', country: 'United Kingdom' },
  { name: 'Hemel Hempstead', country: 'United Kingdom' },
  { name: 'Camberley', country: 'United Kingdom' },
  { name: 'Bishop Auckland', country: 'United Kingdom' },
  { name: 'Bracknell', country: 'United Kingdom' },
  { name: 'Taunton', country: 'United Kingdom' },
  { name: 'Hereford', country: 'United Kingdom' },
  { name: 'Sidcup', country: 'United Kingdom' },
  { name: 'Bebington', country: 'United Kingdom' },
  { name: 'Greenock', country: 'United Kingdom' },
  { name: 'Wellingborough', country: 'United Kingdom' },
  { name: 'Harlow', country: 'United Kingdom' },
  { name: 'Bath', country: 'United Kingdom' },
  { name: 'Letchworth', country: 'United Kingdom' },
  { name: 'Bootle', country: 'United Kingdom' },
  { name: 'Staines', country: 'United Kingdom' },
  { name: 'Dewsbury', country: 'United Kingdom' },
  { name: 'Sittingbourne', country: 'United Kingdom' },
  { name: 'Romford', country: 'United Kingdom' },
  { name: 'Barrow-in-Furness', country: 'United Kingdom' },
  { name: 'Paisley', country: 'United Kingdom' },
  { name: 'Guiseley', country: 'United Kingdom' },
  { name: 'Horsham', country: 'United Kingdom' },
  { name: 'Carshalton', country: 'United Kingdom' },
  { name: 'Reigate', country: 'United Kingdom' },
  { name: 'Bexhill-on-Sea', country: 'United Kingdom' },
  { name: 'Cheadle', country: 'United Kingdom' },
  { name: 'Burgess Hill', country: 'United Kingdom' },
  { name: 'Alloa', country: 'United Kingdom' },
  { name: 'Kirkby', country: 'United Kingdom' },
  { name: 'Loughborough', country: 'United Kingdom' },
  { name: 'Morley', country: 'United Kingdom' },
  { name: 'Coatbridge', country: 'United Kingdom' },
  { name: 'Barry', country: 'United Kingdom' },
  { name: 'Atherton', country: 'United Kingdom' },
  { name: 'Denton', country: 'United Kingdom' },
  { name: 'Melton Mowbray', country: 'United Kingdom' },
  { name: 'Houghton-le-Spring', country: 'United Kingdom' },
  { name: 'Sutton', country: 'United Kingdom' },
  { name: 'Cleethorpes', country: 'United Kingdom' },
  { name: 'Blyth', country: 'United Kingdom' },
  { name: 'Bridlington', country: 'United Kingdom' },
  { name: 'Bicester', country: 'United Kingdom' },
  { name: 'Spalding', country: 'United Kingdom' },
  { name: 'Wigston', country: 'United Kingdom' },
  { name: 'Bridgwater', country: 'United Kingdom' },
  { name: 'Bromsgrove', country: 'United Kingdom' },
  { name: 'Burgess Hill', country: 'United Kingdom' },
  { name: 'Bury St Edmunds', country: 'United Kingdom' },
  { name: 'Camberley', country: 'United Kingdom' },
  { name: 'Cannock', country: 'United Kingdom' },
  { name: 'Carlisle', country: 'United Kingdom' },
  { name: 'Castleford', country: 'United Kingdom' },
  { name: 'Chatham', country: 'United Kingdom' },
  { name: 'Chelmsford', country: 'United Kingdom' },
  { name: 'Chester', country: 'United Kingdom' },
  { name: 'Chichester', country: 'United Kingdom' },
  { name: 'Chippenham', country: 'United Kingdom' },
  { name: 'Chorley', country: 'United Kingdom' },
  { name: 'Cirencester', country: 'United Kingdom' },
  { name: 'Clacton-on-Sea', country: 'United Kingdom' },
  { name: 'Clevedon', country: 'United Kingdom' },
  { name: 'Coalville', country: 'United Kingdom' },
  { name: 'Cockermouth', country: 'United Kingdom' },
  { name: 'Colchester', country: 'United Kingdom' },
  { name: 'Consett', country: 'United Kingdom' },
  { name: 'Corby', country: 'United Kingdom' },
  { name: 'Crawley', country: 'United Kingdom' },
  { name: 'Crewe', country: 'United Kingdom' },
  { name: 'Cromer', country: 'United Kingdom' },
  { name: 'Crowborough', country: 'United Kingdom' },
  { name: 'Crowley', country: 'United Kingdom' },
  { name: 'Cumbernauld', country: 'United Kingdom' },
  { name: 'Darlington', country: 'United Kingdom' },
  { name: 'Dartford', country: 'United Kingdom' },
  { name: 'Darwen', country: 'United Kingdom' },
  { name: 'Daventry', country: 'United Kingdom' },
  { name: 'Dawlish', country: 'United Kingdom' },
  { name: 'Deal', country: 'United Kingdom' },
  { name: 'Denton', country: 'United Kingdom' },
  { name: 'Derby', country: 'United Kingdom' },
  { name: 'Devizes', country: 'United Kingdom' },
  { name: 'Dewsbury', country: 'United Kingdom' },
  { name: 'Doncaster', country: 'United Kingdom' },
  { name: 'Dorchester', country: 'United Kingdom' },
  { name: 'Dover', country: 'United Kingdom' },
  { name: 'Dudley', country: 'United Kingdom' },
  { name: 'Dumfries', country: 'United Kingdom' },
  { name: 'Dunfermline', country: 'United Kingdom' },
  { name: 'Dunstable', country: 'United Kingdom' },
  { name: 'Durham', country: 'United Kingdom' },
  { name: 'East Grinstead', country: 'United Kingdom' },
  { name: 'Eastbourne', country: 'United Kingdom' },
  { name: 'Eastleigh', country: 'United Kingdom' },
  { name: 'Eccles', country: 'United Kingdom' },
  { name: 'Edinburgh', country: 'United Kingdom' },
  { name: 'Ellesmere Port', country: 'United Kingdom' },
  { name: 'Eltham', country: 'United Kingdom' },
  { name: 'Enfield', country: 'United Kingdom' },
  { name: 'Epsom', country: 'United Kingdom' },
  { name: 'Esher', country: 'United Kingdom' },
  { name: 'Evesham', country: 'United Kingdom' },
  { name: 'Exeter', country: 'United Kingdom' },
  { name: 'Exmouth', country: 'United Kingdom' },
  { name: 'Falmouth', country: 'United Kingdom' },
  { name: 'Fareham', country: 'United Kingdom' },
  { name: 'Farnborough', country: 'United Kingdom' },
  { name: 'Farnham', country: 'United Kingdom' },
  { name: 'Faversham', country: 'United Kingdom' },
  { name: 'Felixstowe', country: 'United Kingdom' },
  { name: 'Fleet', country: 'United Kingdom' },
  { name: 'Folkestone', country: 'United Kingdom' },
  { name: 'Formby', country: 'United Kingdom' },
  { name: 'Frimley', country: 'United Kingdom' },
  { name: 'Frome', country: 'United Kingdom' },
  { name: 'Gainsborough', country: 'United Kingdom' },
  { name: 'Gateshead', country: 'United Kingdom' },
  { name: 'Gillingham', country: 'United Kingdom' },
  { name: 'Gloucester', country: 'United Kingdom' },
  { name: 'Godalming', country: 'United Kingdom' },
  { name: 'Goole', country: 'United Kingdom' },
  { name: 'Gosport', country: 'United Kingdom' },
  { name: 'Grantham', country: 'United Kingdom' },
  { name: 'Gravesend', country: 'United Kingdom' },
  { name: 'Grays', country: 'United Kingdom' },
  { name: 'Great Malvern', country: 'United Kingdom' },
  { name: 'Great Yarmouth', country: 'United Kingdom' },
  { name: 'Grimsby', country: 'United Kingdom' },
  { name: 'Guernsey', country: 'United Kingdom' },
  { name: 'Guildford', country: 'United Kingdom' },
  { name: 'Halesowen', country: 'United Kingdom' },
  { name: 'Halifax', country: 'United Kingdom' },
  { name: 'Harlow', country: 'United Kingdom' },
  { name: 'Harrogate', country: 'United Kingdom' },
  { name: 'Harrow', country: 'United Kingdom' },
  { name: 'Hartlepool', country: 'United Kingdom' },
  { name: 'Hastings', country: 'United Kingdom' },
  { name: 'Hatfield', country: 'United Kingdom' },
  { name: 'Havant', country: 'United Kingdom' },
  { name: 'Haywards Heath', country: 'United Kingdom' },
  { name: 'Hemel Hempstead', country: 'United Kingdom' },
  { name: 'Hereford', country: 'United Kingdom' },
  { name: 'Herne Bay', country: 'United Kingdom' },
  { name: 'Hertford', country: 'United Kingdom' },
  { name: 'Hinckley', country: 'United Kingdom' },
  { name: 'Hitchin', country: 'United Kingdom' },
  { name: 'Hoddesdon', country: 'United Kingdom' },
  { name: 'Hornchurch', country: 'United Kingdom' },
  { name: 'Horsham', country: 'United Kingdom' },
  { name: 'Houghton-le-Spring', country: 'United Kingdom' },
  { name: 'Hove', country: 'United Kingdom' },
  { name: 'Huddersfield', country: 'United Kingdom' },
  { name: 'Hull', country: 'United Kingdom' },
  { name: 'Huntingdon', country: 'United Kingdom' },
  { name: 'Hyde', country: 'United Kingdom' },
  { name: 'Ilford', country: 'United Kingdom' },
  { name: 'Ilkeston', country: 'United Kingdom' },
  { name: 'Ipswich', country: 'United Kingdom' },
  { name: 'Irvine', country: 'United Kingdom' },
  { name: 'Isle of Wight', country: 'United Kingdom' },
  { name: 'Jersey', country: 'United Kingdom' },
  { name: 'Jarrow', country: 'United Kingdom' },
  { name: 'Keighley', country: 'United Kingdom' },
  { name: 'Kendal', country: 'United Kingdom' },
  { name: 'Kettering', country: 'United Kingdom' },
  { name: 'Kidderminster', country: 'United Kingdom' },
  { name: 'Kidsgrove', country: 'United Kingdom' },
  { name: 'King\'s Lynn', country: 'United Kingdom' },
  { name: 'Kingston upon Hull', country: 'United Kingdom' },
  { name: 'Kingston upon Thames', country: 'United Kingdom' },
  { name: 'Kirkby', country: 'United Kingdom' },
  { name: 'Kirkcaldy', country: 'United Kingdom' },
  { name: 'Kirkwall', country: 'United Kingdom' },
  { name: 'Knaresborough', country: 'United Kingdom' },
  { name: 'Lancaster', country: 'United Kingdom' },
  { name: 'Lancing', country: 'United Kingdom' },
  { name: 'Leamington Spa', country: 'United Kingdom' },
  { name: 'Leatherhead', country: 'United Kingdom' },
  { name: 'Leeds', country: 'United Kingdom' },
  { name: 'Leicester', country: 'United Kingdom' },
  { name: 'Leigh', country: 'United Kingdom' },
  { name: 'Leighton Buzzard', country: 'United Kingdom' },
  { name: 'Letchworth', country: 'United Kingdom' },
  { name: 'Lewes', country: 'United Kingdom' },
  { name: 'Leyland', country: 'United Kingdom' },
  { name: 'Lichfield', country: 'United Kingdom' },
  { name: 'Lincoln', country: 'United Kingdom' },
  { name: 'Littlehampton', country: 'United Kingdom' },
  { name: 'Liverpool', country: 'United Kingdom' },
  { name: 'Livingston', country: 'United Kingdom' },
  { name: 'Llanelli', country: 'United Kingdom' },
  { name: 'Loughborough', country: 'United Kingdom' },
  { name: 'Loughton', country: 'United Kingdom' },
  { name: 'Lowestoft', country: 'United Kingdom' },
  { name: 'Luton', country: 'United Kingdom' },
  { name: 'Lymington', country: 'United Kingdom' },
  { name: 'Lytham St Annes', country: 'United Kingdom' },
  { name: 'Macclesfield', country: 'United Kingdom' },
  { name: 'Maidenhead', country: 'United Kingdom' },
  { name: 'Maidstone', country: 'United Kingdom' },
  { name: 'Malvern', country: 'United Kingdom' },
  { name: 'Manchester', country: 'United Kingdom' },
  { name: 'Mansfield', country: 'United Kingdom' },
  { name: 'Margate', country: 'United Kingdom' },
  { name: 'Market Harborough', country: 'United Kingdom' },
  { name: 'Marlow', country: 'United Kingdom' },
  { name: 'Middlesbrough', country: 'United Kingdom' },
  { name: 'Middleton', country: 'United Kingdom' },
  { name: 'Milton Keynes', country: 'United Kingdom' },
  { name: 'Minehead', country: 'United Kingdom' },
  { name: 'Mitcham', country: 'United Kingdom' },
  { name: 'Mold', country: 'United Kingdom' },
  { name: 'Morecambe', country: 'United Kingdom' },
  { name: 'Morley', country: 'United Kingdom' },
  { name: 'Motherwell', country: 'United Kingdom' },
  { name: 'Nantwich', country: 'United Kingdom' },
  { name: 'Nelson', country: 'United Kingdom' },
  { name: 'Newark', country: 'United Kingdom' },
  { name: 'Newbury', country: 'United Kingdom' },
  { name: 'Newcastle upon Tyne', country: 'United Kingdom' },
  { name: 'Newcastle-under-Lyme', country: 'United Kingdom' },
  { name: 'Newmarket', country: 'United Kingdom' },
  { name: 'Newport', country: 'United Kingdom' },
  { name: 'Newton Abbot', country: 'United Kingdom' },
  { name: 'Newton Aycliffe', country: 'United Kingdom' },
  { name: 'Northampton', country: 'United Kingdom' },
  { name: 'Northwich', country: 'United Kingdom' },
  { name: 'Norwich', country: 'United Kingdom' },
  { name: 'Nottingham', country: 'United Kingdom' },
  { name: 'Nuneaton', country: 'United Kingdom' },
  { name: 'Oakham', country: 'United Kingdom' },
  { name: 'Oldham', country: 'United Kingdom' },
  { name: 'Ormskirk', country: 'United Kingdom' },
  { name: 'Ossett', country: 'United Kingdom' },
  { name: 'Oxford', country: 'United Kingdom' },
  { name: 'Paignton', country: 'United Kingdom' },
  { name: 'Paisley', country: 'United Kingdom' },
  { name: 'Penzance', country: 'United Kingdom' },
  { name: 'Peterborough', country: 'United Kingdom' },
  { name: 'Peterlee', country: 'United Kingdom' },
  { name: 'Plymouth', country: 'United Kingdom' },
  { name: 'Pontefract', country: 'United Kingdom' },
  { name: 'Poole', country: 'United Kingdom' },
  { name: 'Portsmouth', country: 'United Kingdom' },
  { name: 'Preston', country: 'United Kingdom' },
  { name: 'Pudsey', country: 'United Kingdom' },
  { name: 'Radcliffe', country: 'United Kingdom' },
  { name: 'Ramsgate', country: 'United Kingdom' },
  { name: 'Rawtenstall', country: 'United Kingdom' },
  { name: 'Reading', country: 'United Kingdom' },
  { name: 'Redcar', country: 'United Kingdom' },
  { name: 'Redditch', country: 'United Kingdom' },
  { name: 'Reigate', country: 'United Kingdom' },
  { name: 'Rhyl', country: 'United Kingdom' },
  { name: 'Richmond', country: 'United Kingdom' },
  { name: 'Ripon', country: 'United Kingdom' },
  { name: 'Rochdale', country: 'United Kingdom' },
  { name: 'Rochester', country: 'United Kingdom' },
  { name: 'Romford', country: 'United Kingdom' },
  { name: 'Rotherham', country: 'United Kingdom' },
  { name: 'Rothesay', country: 'United Kingdom' },
  { name: 'Rugby', country: 'United Kingdom' },
  { name: 'Runcorn', country: 'United Kingdom' },
  { name: 'Rushden', country: 'United Kingdom' },
  { name: 'Ryde', country: 'United Kingdom' },
  { name: 'Saffron Walden', country: 'United Kingdom' },
  { name: 'Salford', country: 'United Kingdom' },
  { name: 'Salisbury', country: 'United Kingdom' },
  { name: 'Scarborough', country: 'United Kingdom' },
  { name: 'Scunthorpe', country: 'United Kingdom' },
  { name: 'Seaford', country: 'United Kingdom' },
  { name: 'Seaham', country: 'United Kingdom' },
  { name: 'Selby', country: 'United Kingdom' },
  { name: 'Sevenoaks', country: 'United Kingdom' },
  { name: 'Sheffield', country: 'United Kingdom' },
  { name: 'Sherborne', country: 'United Kingdom' },
  { name: 'Shildon', country: 'United Kingdom' },
  { name: 'Shoreham-by-Sea', country: 'United Kingdom' },
  { name: 'Shrewsbury', country: 'United Kingdom' },
  { name: 'Sidcup', country: 'United Kingdom' },
  { name: 'Sittingbourne', country: 'United Kingdom' },
  { name: 'Skegness', country: 'United Kingdom' },
  { name: 'Skelmersdale', country: 'United Kingdom' },
  { name: 'Sleaford', country: 'United Kingdom' },
  { name: 'Slough', country: 'United Kingdom' },
  { name: 'Solihull', country: 'United Kingdom' },
  { name: 'Southampton', country: 'United Kingdom' },
  { name: 'Southend-on-Sea', country: 'United Kingdom' },
  { name: 'Southport', country: 'United Kingdom' },
  { name: 'South Shields', country: 'United Kingdom' },
  { name: 'Spalding', country: 'United Kingdom' },
  { name: 'Stafford', country: 'United Kingdom' },
  { name: 'Staines', country: 'United Kingdom' },
  { name: 'Stamford', country: 'United Kingdom' },
  { name: 'Stevenage', country: 'United Kingdom' },
  { name: 'Stockport', country: 'United Kingdom' },
  { name: 'Stockton-on-Tees', country: 'United Kingdom' },
  { name: 'Stoke-on-Trent', country: 'United Kingdom' },
  { name: 'Stourbridge', country: 'United Kingdom' },
  { name: 'Stratford-upon-Avon', country: 'United Kingdom' },
  { name: 'Strood', country: 'United Kingdom' },
  { name: 'Stroud', country: 'United Kingdom' },
  { name: 'Sunderland', country: 'United Kingdom' },
  { name: 'Sutton Coldfield', country: 'United Kingdom' },
  { name: 'Sutton-in-Ashfield', country: 'United Kingdom' },
  { name: 'Swadlincote', country: 'United Kingdom' },
  { name: 'Swansea', country: 'United Kingdom' },
  { name: 'Swindon', country: 'United Kingdom' },
  { name: 'Tamworth', country: 'United Kingdom' },
  { name: 'Taunton', country: 'United Kingdom' },
  { name: 'Telford', country: 'United Kingdom' },
  { name: 'Tenby', country: 'United Kingdom' },
  { name: 'Tewkesbury', country: 'United Kingdom' },
  { name: 'Thame', country: 'United Kingdom' },
  { name: 'Thatcham', country: 'United Kingdom' },
  { name: 'Thetford', country: 'United Kingdom' },
  { name: 'Thornaby', country: 'United Kingdom' },
  { name: 'Tiverton', country: 'United Kingdom' },
  { name: 'Tonbridge', country: 'United Kingdom' },
  { name: 'Torquay', country: 'United Kingdom' },
  { name: 'Totton', country: 'United Kingdom' },
  { name: 'Trowbridge', country: 'United Kingdom' },
  { name: 'Truro', country: 'United Kingdom' },
  { name: 'Tunbridge Wells', country: 'United Kingdom' },
  { name: 'Tynemouth', country: 'United Kingdom' },
  { name: 'Uckfield', country: 'United Kingdom' },
  { name: 'Ulverston', country: 'United Kingdom' },
  { name: 'Uxbridge', country: 'United Kingdom' },
  { name: 'Vale of Glamorgan', country: 'United Kingdom' },
  { name: 'Wakefield', country: 'United Kingdom' },
  { name: 'Wallasey', country: 'United Kingdom' },
  { name: 'Walsall', country: 'United Kingdom' },
  { name: 'Waltham Abbey', country: 'United Kingdom' },
  { name: 'Waltham Cross', country: 'United Kingdom' },
  { name: 'Walthamstow', country: 'United Kingdom' },
  { name: 'Walton-on-Thames', country: 'United Kingdom' },
  { name: 'Wandsworth', country: 'United Kingdom' },
  { name: 'Warrington', country: 'United Kingdom' },
  { name: 'Warwick', country: 'United Kingdom' },
  { name: 'Washington', country: 'United Kingdom' },
  { name: 'Watford', country: 'United Kingdom' },
  { name: 'Wellingborough', country: 'United Kingdom' },
  { name: 'Wells', country: 'United Kingdom' },
  { name: 'Welwyn Garden City', country: 'United Kingdom' },
  { name: 'West Bromwich', country: 'United Kingdom' },
  { name: 'Weston-super-Mare', country: 'United Kingdom' },
  { name: 'Weymouth', country: 'United Kingdom' },
  { name: 'Whitehaven', country: 'United Kingdom' },
  { name: 'Widnes', country: 'United Kingdom' },
  { name: 'Wigan', country: 'United Kingdom' },
  { name: 'Wigston', country: 'United Kingdom' },
  { name: 'Wilmslow', country: 'United Kingdom' },
  { name: 'Wimbledon', country: 'United Kingdom' },
  { name: 'Winchester', country: 'United Kingdom' },
  { name: 'Windsor', country: 'United Kingdom' },
  { name: 'Winsford', country: 'United Kingdom' },
  { name: 'Wisbech', country: 'United Kingdom' },
  { name: 'Woking', country: 'United Kingdom' },
  { name: 'Wokingham', country: 'United Kingdom' },
  { name: 'Wolverhampton', country: 'United Kingdom' },
  { name: 'Worcester', country: 'United Kingdom' },
  { name: 'Workington', country: 'United Kingdom' },
  { name: 'Worksop', country: 'United Kingdom' },
  { name: 'Worthing', country: 'United Kingdom' },
  { name: 'Wrexham', country: 'United Kingdom' },
  { name: 'Wymondham', country: 'United Kingdom' },
  { name: 'Yeovil', country: 'United Kingdom' },
  { name: 'York', country: 'United Kingdom' },
  { name: 'Ystrad Mynach', country: 'United Kingdom' }
];

export const useLocationAutocomplete = (options: UseLocationAutocompleteOptions = {}) => {
  const { debounceMs = 300, minLength = 2 } = options;
  
  const [query, setQuery] = useState('');
  const [suggestions, setSuggestions] = useState<LocationSuggestion[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isOpen, setIsOpen] = useState(false);
  const [selectedIndex, setSelectedIndex] = useState(-1);

  // Local search function using city database
  const searchLocations = useCallback(async (searchQuery: string) => {
    if (searchQuery.length < minLength) {
      setSuggestions([]);
      setIsOpen(false);
      return;
    }

    setIsLoading(true);
    setIsOpen(true);

    // Simulate API delay
    await new Promise(resolve => setTimeout(resolve, 100));

    try {
      const filteredCities = CITY_DATABASE.filter(city => 
        city.name.toLowerCase().includes(searchQuery.toLowerCase()) ||
        (city.state && city.state.toLowerCase().includes(searchQuery.toLowerCase())) ||
        city.country.toLowerCase().includes(searchQuery.toLowerCase())
      ).slice(0, 5);

      const locationSuggestions: LocationSuggestion[] = filteredCities.map((city, index) => ({
        id: `${city.name}-${city.state || ''}-${city.country}-${index}`,
        name: city.name,
        country: city.country,
        state: city.state,
        displayName: `${city.name}${city.state ? `, ${city.state}` : ''}, ${city.country}`
      }));
      
      setSuggestions(locationSuggestions);
    } catch (error) {
      console.error('Error filtering location suggestions:', error);
      setSuggestions([]);
    } finally {
      setIsLoading(false);
    }
  }, [minLength]);

  // Debounce effect
  useEffect(() => {
    const timeoutId = setTimeout(() => {
      if (query.trim()) {
        searchLocations(query.trim());
      } else {
        setSuggestions([]);
        setIsOpen(false);
      }
    }, debounceMs);

    return () => clearTimeout(timeoutId);
  }, [query, debounceMs, searchLocations]);

  const handleInputChange = (value: string) => {
    setQuery(value);
    setSelectedIndex(-1);
  };

  const handleSuggestionSelect = (suggestion: LocationSuggestion) => {
    setQuery(suggestion.displayName);
    setSuggestions([]);
    setIsOpen(false);
    setSelectedIndex(-1);
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (!isOpen || suggestions.length === 0) return;

    switch (e.key) {
      case 'ArrowDown':
        e.preventDefault();
        setSelectedIndex(prev => 
          prev < suggestions.length - 1 ? prev + 1 : 0
        );
        break;
      case 'ArrowUp':
        e.preventDefault();
        setSelectedIndex(prev => 
          prev > 0 ? prev - 1 : suggestions.length - 1
        );
        break;
      case 'Enter':
        e.preventDefault();
        if (selectedIndex >= 0 && selectedIndex < suggestions.length) {
          handleSuggestionSelect(suggestions[selectedIndex]);
        }
        break;
      case 'Escape':
        setIsOpen(false);
        setSelectedIndex(-1);
        break;
    }
  };

  const closeSuggestions = () => {
    setIsOpen(false);
    setSelectedIndex(-1);
  };

  return {
    query,
    suggestions,
    isLoading,
    isOpen,
    selectedIndex,
    handleInputChange,
    handleSuggestionSelect,
    handleKeyDown,
    closeSuggestions,
    setQuery,
    setIsOpen,
    setSelectedIndex
  };
};
